name: CI

on: [ push ]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v2

            -   uses: actions/setup-node@v2
                with:
                    node-version: '14'

            -   uses: pnpm/action-setup@v2
                with:
                    version: '^6.7'
                    run_install: true

            -   run: pnpm test

            -   name: Prettify package.json
                run: ./node_modules/.bin/prettier-package-json --use-tabs --list-different
