name: Release version to npm

on:
    workflow_dispatch:
    push:
        tags:
            - '*'

permissions:
    id-token: write  # Required for OIDC in npm
    contents: read

jobs:
    ci:
        uses: "./.github/workflows/ci.yml"
    deploy:
        name: deploy
        needs: [ci]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v6

            -   uses: actions/setup-node@v6
                with:
                    node-version: '24'
                    registry-url: "https://registry.npmjs.org"

            -   uses: pnpm/action-setup@v3
                with:
                    version: 'latest'
                    run_install: true

            -   name: Set version number in package.json
                run: pnpm version from-git --no-git-tag-version

            -   name: Publish package
                run: npm publish --ignore-scripts
                env:
                    NODE_AUTH_TOKEN: "" # explicitly clear to use OIDC
